import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ActiveSectionContextProvider, {
  ActiveSectionContext,
} from "@/ui/active-section-context";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Container from "@/components/container";
import Logo from "@/components/logo";
import ThemeContextProvider from "@/ui/theme-context";
import ThemeSwitch from "@/components/theme-switch";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portofolio | Harsena Argretya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <ActiveSectionContextProvider>
          <body
            className={`${inter.className} md:bg-gray-950 bg-zinc-900 dark:bg-white dark:md:bg-zinc-200 text-white min-h-screen`}
          >
            <Container>
              {/* <Logo /> */}
              <ThemeSwitch />
              <Header />
              {children}
              <Analytics />
              <Footer />
            </Container>
          </body>
        </ActiveSectionContextProvider>
      </ThemeContextProvider>
    </html>
  );
}
