import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ActiveSectionContextProvider, {
  ActiveSectionContext,
} from "@/ui/active-section-context";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Container from "@/components/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ActiveSectionContextProvider>
        <body
          className={`${inter.className} bg-gray-950 text-white min-h-screen`}
        >
          <Container>
            <Header />
            {children}
            <Footer />
          </Container>
        </body>
      </ActiveSectionContextProvider>
    </html>
  );
}
